# -*- coding: utf-8 -*-
"""RethiSaliya_stage1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3a-GpRAALNe52vUGixGPYRp0uy_G8YQ
"""



num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
operator = input("Enter operator (+, -, *, /): ")

if operator == "+":
    result = num1 + num2
elif operator == "-":
    result = num1 - num2
elif operator == "*":
    result = num1 * num2
elif operator == "/":
    if num2 == 0:
        print("Error: Division by zero is not allowed")
        result = None
    else:
        result = num1 / num2
else:
    print("Invalid operator")
    result = None

if result is not None:
    print("Result =", result)