# -*- coding: utf-8 -*-
"""RethiSaliya_stage3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3a-GpRAALNe52vUGixGPYRp0uy_G8YQ
"""



name = input("Enter student name: ")

mark1 = float(input("Enter marks for subject 1 (0-100): "))
mark2 = float(input("Enter marks for subject 2 (0-100): "))
mark3 = float(input("Enter marks for subject 3 (0-100): "))

total = mark1 + mark2 + mark3
percentage = (total / 300) * 100

if percentage >= 75:
    grade = "A"
elif percentage >= 60:
    grade = "B"
elif percentage >= 40:
    grade = "C"
else:
    grade = "F"

print("\n----- Result -----")
print("Name:", name)
print("Total:", total, "/300")
print("Percentage:", round(percentage, 2), "%")
print("Grade:", grade)